default_language_version:
  python: python3.7

fail_fast: true

repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v2.5.0
  hooks:
  - id: trailing-whitespace
  - id: fix-encoding-pragma
  - id: check-yaml
  - id: check-toml
- repo: https://github.com/psf/black
  rev: 19.10b0
  hooks:
  - id: black
