dist: xenial
addons:
  chrome: stable
env:
  global:
    - secure: BnDXWqWxRfroBNEk/nXZ4zLrml7OsQ36yfCN8gGsZhHvKswJfnRuE5l1SHkDXZMl/m0XA14y1EgNjeRbbVhFRkfUis7cmS/+z2Iz2+XNeH0w4gHFk8FMUijeL5Dhsem+H/tcxdPfQghIB4uvnp8uiVVVMay7rD7QRfHKW8uvw6kxYpMRAtdaSxW+8Sm+7Dbkt/tKyWVUzl1rJThCkG9vQHoN4EQ4IewzGXzgBP+z8irDosrLYDQCyIfQooRqUz+conOAPJ5VOVfcEMNZ+dQ5dhVjIMzGDg2BBKVRiPTlvmoKB31Eaj/I8RbJZTOQIwrNu62lKkvkY3QUP8BzoQ9FQ/+32b2vGJrOnmguTPjHtgQlXoFHMshMF25/JhtesjUp1tN7ATSfdbc0bLaIBIPWp6jiTq+Z0VB21w11zjBYgi97lROtEPBFcg6CjFOrf3Tr1A1v3surHU9gKX9rUXuIWycyf55MDH3/FAzjoikOULQZ5edO7i2yzzIBM2LNaXXJ+kC8VpqGIQ1Y/nHYln/e0vHyacrgi5f85fEMF1P3KkpJOgYUCOeWU3IJefxlpBB9uYn/Lia3duH3sp4xjca6GQ6Wm2emrxt+aaOO3OqiLqXiN7Ig+8X8/5UdUBqHqbj5/Zfy/HAhd1B571HKbhH9raAUa1/UMzwPrWNrPvGV/20=
language: python
python:
- 3.8
before_install:
- pip install --upgrade pip
- pip install poetry
- rm -rf ~/.nvm && git clone https://github.com/creationix/nvm.git ~/.nvm && (cd ~/.nvm && git checkout `git describe --abbrev=0 --tags`) && source ~/.nvm/nvm.sh && nvm install $TRAVIS_NODE_VERSION
install:
- poetry install
before_script:
- CHROME_MAIN_VERSION=`google-chrome-stable --version | sed -E 's/(^Google Chrome
  |\.[0-9]+ )//g'`
- CHROMEDRIVER_VERSION=`curl -s "https://chromedriver.storage.googleapis.com/LATEST_RELEASE_$CHROME_MAIN_VERSION"`
- curl "https://chromedriver.storage.googleapis.com/${CHROMEDRIVER_VERSION}/chromedriver_linux64.zip"
  -O
- unzip chromedriver_linux64.zip -d ~/bin
- npm install -D @percy/script
script: make test
deploy:
  provider: heroku
  app: dash-covid19-pro
  strategy: git
  on:
    tags: true
    python: 3.8
  api_key:
    secure: bG2CMZgk4zPAPzvnHB08/aXYEDpJD+cimZRF8+QrDXVICe5La//AiBPEPWm0lwYgVH8QBAmRtdDxINSaVIN1jMUX4ZDLiSS9SpXevJGJP7xTYS/C/ff7I1ZudjtCbwAnS+FvPErqjXAi6mP4IC+cBi7ofWWT88dU+alVAxW1AtD8or4ODQKQySoZZbsfD/iLuYWWtC6TF7tzEW6S064vcR+lSYba7AvgYffTLbfEsPpFeVpPGpGkZH06AZmhZ0NvEDc3FFoVuL6BCO+FXVTUp7D1itxUReo+FgsIhipX23RBIgzYOTldA9AppEsIxYvKYsPyweFPjlCizO5WTJsVsTf4C5Smp2qD/YRGjRBX1N/qeJak4Rl0bi6ylXvF/+vt2Jf026vA6qHXZ2uoeqQVdhKQOlh/Cr4jktVuSAs+qfztxTeFMqM5/F64g/egJIHYmGkORvRFKUJzO9Eyqp33GgmlQNSD3BqS+p+h2idDU1yfQndKbegLFp1uUrVJ987bqyL/DY6OkYOvMdpB3fps8ss+hi6ppuThsqXsfXcjrkW3TH/V/LaYvHosBSz3QI92gnEmVi/I/IP2/7L0ShBShgoc1zx8tj5iN4cQyiUqQZl+e+gbqePJ2dggikIceh/vJEUQQKjy+9St/5j+x/vluNixcq1pzUWj6CZn7wXqoqc=
after_success:
- codecov
